### ISSUE TITLE
有赞物流接口问题

### ISSUE THREAD

**Issue by longteng429** [rayqian/youzan-sdk#3]
你好，

我使用物流流转信息查询接口，发现如果一个订单分成两个包裹，每个包裹使用不同的物流公司，但是在使用如下接口的时候，只返回第一个包裹的物流单号,这个是我获取的方式不对，还是有赞的API不支持返回两个以上物流的信息吗？
使用的物流接口API：[kdt.logistics.trace.search](https://open.youzan.com/apidetail?method=kdt.logistics.trace.search&apiId=6970) 物流流转信息查询

谢谢

**Comment by rayqian** [comment]
下次这种问题建议你去官方论坛 https://bbs.youzan.com  发帖询问，我先帮你问问看啥情况。
